create table LOGMNR_PARTOBJ$
(
    PARTTYPE     NUMBER,
    PARTCNT      NUMBER,
    PARTKEYCOLS  NUMBER,
    FLAGS        NUMBER,
    DEFTS#       NUMBER,
    DEFPCTFREE   NUMBER,
    DEFPCTUSED   NUMBER,
    DEFPCTTHRES  NUMBER,
    DEFINITRANS  NUMBER,
    DEFMAXTRANS  NUMBER,
    DEFTINIEXTS  NUMBER,
    DEFEXTSIZE   NUMBER,
    DEFMINEXTS   NUMBER,
    DEFMAXEXTS   NUMBER,
    DEFEXTPCT    NUMBER,
    DEFLISTS     NUMBER,
    DEFGROUPS    NUMBER,
    DEFLOGGING   NUMBER,
    SPARE1       NUMBER,
    SPARE2       NUMBER,
    SPARE3       NUMBER,
    DEFINCLCOL   NUMBER,
    PARAMETERS   VARCHAR2(3000),
    OBJ#         NUMBER not null,
    LOGMNR_UID   NUMBER(22),
    LOGMNR_FLAGS NUMBER(22),
    constraint LOGMNR_PARTOBJ$_PK
        primary key (LOGMNR_UID, OBJ#)
)
/

create index LOGMNR_I1PARTOBJ$
    on LOGMNR_PARTOBJ$ (LOGMNR_UID, OBJ#)
/

