create table LOGSTDBY$APPLY_PROGRESS
(
    XIDUSN      NUMBER,
    XIDSLT      NUMBER,
    XIDSQN      NUMBER,
    COMMIT_SCN  NUMBER,
    COMMIT_TIME DATE,
    SPARE1      NUMBER,
    SPARE2      NUMBER,
    SPARE3      VARCHAR2(2000)
)
/

