create table LOGSTDBY$SKIP_TRANSACTION
(
    XIDUSN     NUMBER,
    XIDSLT     NUMBER,
    XIDSQN     NUMBER,
    ACTIVE     NUMBER,
    COMMIT_SCN NUMBER,
    SPARE2     NUMBER,
    SPARE3     VARCHAR2(2000),
    CON_NAME   VARCHAR2(384)
)
/

