create table LOGSTDBY$EVENTS
(
    EVENT_TIME  TIMESTAMP(6) not null,
    CURRENT_SCN NUMBER,
    COMMIT_SCN  NUMBER,
    XIDUSN      NUMBER,
    XIDSLT      NUMBER,
    XIDSQN      NUMBER,
    ERRVAL      NUMBER,
    EVENT       VARCHAR2(2000),
    FULL_EVENT  CLOB,
    ERROR       VARCHAR2(2000),
    SPARE1      NUMBER,
    SPARE2      NUMBER,
    SPARE3      VARCHAR2(2000),
    CON_NAME    VARCHAR2(30),
    CON_ID      NUMBER
)
/

create index LOGSTDBY$EVENTS_IND
    on LOGSTDBY$EVENTS (EVENT_TIME)
/

create index LOGSTDBY$EVENTS_IND_SCN
    on LOGSTDBY$EVENTS (COMMIT_SCN)
/

create index LOGSTDBY$EVENTS_IND_XID
    on LOGSTDBY$EVENTS (XIDUSN, XIDSLT, XIDSQN)
/

