create table SCHEDULER_JOB_ARGS_TBL
(
    OWNER             VARCHAR2(128),
    JOB_NAME          VARCHAR2(128),
    ARGUMENT_NAME     VARCHAR2(128),
    ARGUMENT_POSITION NUMBER,
    ARGUMENT_TYPE     VARCHAR2(257),
    VALUE             VARCHAR2(4000),
    ANYDATA_VALUE     SYS.ANYDATA,
    OUT_ARGUMENT      VARCHAR2(5)
)
/

